name = "SimpleQuantum"
uuid = "7c07e4e5-e402-48af-840a-a11b8ea3e28c"
authors = ["Tomas Polakovic <tom.polakovic@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
RangeHelpers = "3a07dd3d-1c52-4395-8858-40c6328157db"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
